### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by TizianoCoroneo** [rudderlabs/rudder-integration-appsflyer-ios#28]
The latest version of the Rudderstack SDK is 2.4.3, and the current definition in the `Package.swift` of `from: "1.0.0"` will avoid updating to major versions.
Similarly, the latest version of the AppsFlyer SDK is `6.12.3` that is explicitly excluded from the specified range: `"6.12.2"..<"6.12.3"`.

Is this library still supported? Why is the latest version of AppsFlyer explicitly excluded? Should I copy paste the content of this library into our project? Should I roll my own?

**Comment by 1abhishekpandey** [comment]
Hey @TizianoCoroneo,
I apologize for the delay in my response. Please find the following clarifications:

1. Our iOS SDK v2 (version 2.4.3) is currently in beta. We recommend opting for the v1 SDKs [v1.25.2](https://github.com/rudderlabs/rudder-sdk-ios/releases/tag/v1.25.2) for a better experience and utilise this `Rudder-Appsflyer` integration.
2. For the iOS SDK v2, we have a distinct `RudderAppsFlyer` integration. Refer to that repo: https://github.com/rudderlabs/rudder-integration-appsflyer-swift.
3. During our last integration work, we tested it with `AppsFlyerFramework` SDK `v6.12.2`. Therefore, we have set restrictions to that specific version in the `Package.swift`.
5. Currently, you have the option to utilize the latest version of the AppsFlyerFramework SDK, which is version 6.13.0, through CocoaPods. Kindly inform us if that works for you.
6. Yes, this library is still actively supported.

Can you please answer a few queries:

1. Would you prefer to use the latest version of the AppsFlyerFramework SDK, i.e., [6.13.0](https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/6.13.0), or [6.12.3](https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/6.12.3) through SMP only? If you encounter any issues with the current version (v6.12.2), please inform us.

**Comment by TizianoCoroneo** [comment]
We always strive to stay on latest versions of everything, and following that we got rid of Cocoapods in favor of SPM almost 2 years ago. Yes I would prefer to have SPM support.

I understand pinning the version to the last version that you tested, but I think that allowing at least patch version bumps, like from 6.12.2 to 6.12.3, should be allowed.

I'll refactor our project to use Rudderstack v1 for the moment, thanks for the info.

**Comment by 1abhishekpandey** [comment]
To inform you, we plan to update the current restriction in the Swift Package Manager (SPM) so that you can utilise the latest version of the AppsFlyer SDK. The ETA for this update is late next week. I'll keep you updated.

**Comment by 1abhishekpandey** [comment]
Hey @TizianoCoroneo,
We updated the SPM restriction to allow AppsFlyer SDK versions up to less than v7.0.0. Please use the latest version, [2.5.0](https://github.com/rudderlabs/rudder-integration-appsflyer-ios/releases/tag/v2.5.0)."

**Comment by 1abhishekpandey** [comment]
Hey @TizianoCoroneo,
Could you please confirm if it's appropriate to close this issue?

**Comment by TizianoCoroneo** [comment]
Works, thank you!
